apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-muei
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-muei
    app.kubernetes.io/part-of: test-app-laui
  name: devfile-sample-hello-world-muei
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world-muei
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world-muei
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-xscr-tenant/test-app-laui/devfile-sample-hello-world-muei@sha256:e3ae72e3a2c987f53b2a39b04f002060a56aac84406e3df2bbdff4cdb98a396a
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
